# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 34bc07bd3b53e6388a4948c6f057a4eafeb5edfce8657168f8001aca312bcf39f3a53378f99e2d2a278eab6b25f0766cacffbd3d7e3bfd759ab70e68ee48350f

test:
  secret_key_base: e9a6810d5d078889d674cfdc080f47eb907064a7397a8c21f09dce0bc177936e241e2dea02e56d9b9cf46b79d68103e9ca11f5b5d822bca6e1297c057992acc6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
